// server/src/plans/plans.config.ts
export const PLANS = {
  free: {
    id: 'free',
    name: 'Free',
    price: 0,
    priceYearly: 0,
    description: 'Perfect for getting started with basic security scanning',
    scansPerDay: 5,
    concurrentScans: 1,
    historyRetentionDays: 7,
    aiFixesEnabled: false,
    exportReportsEnabled: true,
    deepScanEnabled: false,
    prioritySupport: false,
    customRulesEnabled: false,
    maxTeamMembers: 1,
    apiAccessEnabled: false,
    maxWebsites: 1,
    scanTimeoutSeconds: 60,
    advancedAnalytics: false,
    customReportsEnabled: false,
    webhookIntegration: false,
    ssoEnabled: false,
    auditLogsEnabled: false,
    whiteLabelEnabled: false,
    unlimitedScans: false,
    unlimitedWebsites: false,
    unlimitedTeam: false,
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    price: 29,
    priceYearly: 290,
    description: 'Ideal for professional developers and small teams',
    scansPerDay: 100,
    concurrentScans: 5,
    historyRetentionDays: 90,
    aiFixesEnabled: true,
    exportReportsEnabled: true,
    deepScanEnabled: true,
    prioritySupport: true,
    customRulesEnabled: true,
    maxTeamMembers: 10,
    apiAccessEnabled: true,
    maxWebsites: 25,
    scanTimeoutSeconds: 120,
    advancedAnalytics: true,
    customReportsEnabled: true,
    webhookIntegration: true,
    ssoEnabled: false,
    auditLogsEnabled: true,
    whiteLabelEnabled: false,
    unlimitedScans: false,
    unlimitedWebsites: false,
    unlimitedTeam: false,
  },
  extra: {
    id: 'extra',
    name: 'Extra',
    price: 79,
    priceYearly: 790,
    description: 'For enterprises and power users needing maximum capabilities',
    scansPerDay: Infinity,
    concurrentScans: Infinity,
    historyRetentionDays: 365,
    aiFixesEnabled: true,
    exportReportsEnabled: true,
    deepScanEnabled: true,
    prioritySupport: true,
    customRulesEnabled: true,
    maxTeamMembers: Infinity,
    apiAccessEnabled: true,
    maxWebsites: Infinity,
    scanTimeoutSeconds: 300,
    advancedAnalytics: true,
    customReportsEnabled: true,
    webhookIntegration: true,
    ssoEnabled: true,
    auditLogsEnabled: true,
    whiteLabelEnabled: true,
    unlimitedScans: true,
    unlimitedWebsites: true,
    unlimitedTeam: true,
  },
} as const;

export type PlanId = keyof typeof PLANS;
export type Plan = (typeof PLANS)[PlanId];
